[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "fre_make_chatbot"
version = "0.2.0"
requires-python = ">=3.11"
dependencies = [
  "langchain",
  "langchain-core",
  "langchain-community",
  "langchain-text-splitters",
  "langchain-ollama",
  "langchain-postgres",
  "pgvector",
  "chromadb",
  "psycopg2-binary",
  "streamlit",
  "requests",
  "nest-asyncio"
]
readme = "README.md"
description = "Draft version of FRE make 'mini' chatbot, based on Langchain, Ollama, and Llama 3.1"
