[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "minichatbot"
version = "0.0.0"
requires-python = ">=3.11"
dependencies = [
   "chromadb",
   "langchain",
   "langchain-core",
   "langchain-ollama",
   "langchain-chroma",
   "langchain-community",
   "pymilvus"
]
