<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<doxygen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="compound.xsd" version="1.8.14">
  <compounddef id="build" kind="page">
    <compoundname>build</compoundname>
    <title>Building and Installation</title>
    <innerpage refid="install">Installation</innerpage>
    <innerpage refid="autotools">Building with Autotools</innerpage>
    <innerpage refid="cmake">Building with CMake</innerpage>
    <briefdescription>
<para>Information about the build systems and how to build and install. </para>    </briefdescription>
    <detaileddescription>
<para>Information about the build systems and how to build and install</para><para><ref refid="install" kindref="compound">Installation</ref></para><para><ref refid="autotools" kindref="compound">Building with Autotools</ref></para><para><ref refid="cmake" kindref="compound">Building with CMake</ref> </para>    </detaileddescription>
  </compounddef>
</doxygen>
